#!/bin/bash

NAME=$1

heroku create $NAME
git remote add $NAME git@heroku.com:$NAME.git

heroku config:add --app $NAME \
  INSTANCE_NAME=$NAME \
  APP_HOST=$NAME.heroku.com \
  GMAIL_SMTP_USER=username@gmail.com \
  GMAIL_SMTP_PASSWORD='password' \
  AWS_S3_ACCESS_KEY_ID=XXX \
  AWS_S3_SECRET_ACCESS_KEY=XXX \


git push $NAME master:master

heroku rake db:migrate --app $NAME
